// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxyxxosfszilejozhvfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4eXh4b3Nmc3ppbGVqb3podmZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTU0NTIsImV4cCI6MjA3Mzg3MTQ1Mn0.f5CNFsvMDAxXQk_O3eCF5mLVlMuvytVj7L6ISMP-HAM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});